version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  celery_worker:
    build: ./backend
    container_name: celery_worker
    command: celery -A backend worker --loglevel=info --concurrency=1 --max-tasks-per-child=1
    depends_on:
      - redis
      - backend
      - db
    env_file:
      - ./.env
  
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  
  db:
    image: pgvector/pgvector:pg18
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql
    ports: 
      - "5432:5432"

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.prod
    ports:
      - "80:8080"
    depends_on:
      - backend

volumes:
  postgres_data: