version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
  
  worker:
    build: ./backend
    container_name: celery-worker
    command: celery -A backend worker -l info
    depends_on:
      - redis
      - backend
      - db
    env_file:
      - ./.env
  
  beat:
    build: ./backend
    container_name: celery-beat
    command: celery -A backend beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - backend
      - db
    env_file:
      - ./.env
  
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  
  db:
    image: pgvector/pgvector:pg18
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql
    ports: 
      - "5432:5432"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - react_build:/app/build
  nginx:
    image: nginx:alpine
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  react_build: