# Generated by Django 5.0.2 on 2024-09-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('name', models.CharField(max_length=300, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Actors',
            },
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('name', models.CharField(max_length=300, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Directors',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='StreamingOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('homePage', models.URLField()),
                ('lightThemeImage', models.ImageField(upload_to='')),
                ('darkThemeImage', models.ImageField(upload_to='')),
                ('whiteImage', models.ImageField(upload_to='')),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'StreamingOptions',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imdbId', models.CharField(max_length=20, unique=True)),
                ('tmdbId', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('releaseYear', models.IntegerField()),
                ('originalTitle', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('api_rating', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('cast', models.ManyToManyField(to='base.actors')),
                ('directors', models.ManyToManyField(to='base.directors')),
                ('genres', models.ManyToManyField(to='base.genres')),
                ('languages', models.ManyToManyField(to='base.languages')),
            ],
            options={
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.AddConstraint(
            model_name='streamingoptions',
            constraint=models.UniqueConstraint(fields=('id', 'type'), name='unique_streaming_type'),
        ),
        migrations.AddField(
            model_name='movies',
            name='streamingOptions',
            field=models.ManyToManyField(to='base.streamingoptions'),
        ),
    ]
