# Generated by Django 5.0.2 on 2024-12-06 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='StreamingProvider',
            fields=[
                ('provider_id', models.IntegerField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'StreamingProviders',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField(null=True)),
                ('release_date', models.DateField()),
                ('original_title', models.CharField(max_length=100, null=True)),
                ('poster', models.URLField()),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('popularity', models.FloatField(null=True)),
                ('vote_count', models.IntegerField(null=True)),
                ('vote_average', models.FloatField(null=True)),
                ('adult', models.BooleanField()),
                ('genres', models.ManyToManyField(to='base.genres')),
                ('original_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.languages')),
            ],
            options={
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='StreamingOptionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaming_services', to='base.movies')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.streamingprovider')),
            ],
            options={
                'verbose_name_plural': 'StreamingOptions',
            },
        ),
        migrations.CreateModel(
            name='WatchedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_date', models.DateTimeField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
