# Generated by Django 5.0.2 on 2025-11-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='trailer_key',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='trailer_site',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
