# Generated by Django 5.0.2 on 2025-11-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_movies_trailer_key_movies_trailer_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='imdb_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='imdb_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='imdb_votes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='metacritic_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='ratings_updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='rotten_tomatoes_rating',
            field=models.IntegerField(null=True),
        ),
    ]
