# Generated by Django 5.0.2 on 2025-12-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_movies_imdb_id_movies_imdb_rating_movies_imdb_votes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='trailer_official',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='adult',
            field=models.BooleanField(null=True),
        ),
    ]
