# Generated by Django 5.0.2 on 2025-12-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_movies_trailer_official_alter_movies_adult'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='streaming_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
