# Generated by Django 5.0.2 on 2025-12-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_movies_streaming_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('popularity', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Actors',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('popularity', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Directors',
            },
        ),
        migrations.AddField(
            model_name='movies',
            name='cast',
            field=models.ManyToManyField(related_name='movies', to='base.actor'),
        ),
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.ManyToManyField(related_name='movies', to='base.director'),
        ),
    ]
