# Generated by Django 5.0.2 on 2025-12-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_movies_cast_movieactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='cast',
            field=models.ManyToManyField(related_name='movies', through='base.MovieActor', to='base.actor'),
        ),
    ]
