# Generated by Django 5.0.2 on 2026-02-12 01:26

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_movies_cast'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborativeVector',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContentBasedVector',
            fields=[
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.movies')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
            ],
        ),
    ]
