# Generated by Django 5.0.2 on 2026-02-12 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_collaborativevector_contentbasedvector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentbasedvector',
            name='movie_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='content_based_vector', serialize=False, to='base.movies'),
        ),
    ]
