# Generated by Django 5.0.2 on 2026-02-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_contentbasedvector_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieactor',
            name='character',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
