FROM node:20-alpine AS frontend_builder

WORKDIR /app/frontend

COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci

COPY frontend/ ./
RUN npm run build

FROM nginx:alpine

COPY nginx/nginx-setup.conf /etc/nginx/conf.d/default.conf
COPY --from=frontend_builder /app/frontend/build /var/www/react
